// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Полная информация о модели (как в БД)
type ModelInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoId           string                 `protobuf:"bytes,3,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Filename         string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	InputTokenPrice  int64                  `protobuf:"varint,5,opt,name=input_token_price,json=inputTokenPrice,proto3" json:"input_token_price,omitempty"`
	OutputTokenPrice int64                  `protobuf:"varint,6,opt,name=output_token_price,json=outputTokenPrice,proto3" json:"output_token_price,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ModelInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ModelInfo) GetInputTokenPrice() int64 {
	if x != nil {
		return x.InputTokenPrice
	}
	return 0
}

func (x *ModelInfo) GetOutputTokenPrice() int64 {
	if x != nil {
		return x.OutputTokenPrice
	}
	return 0
}

func (x *ModelInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ModelItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelItems) Reset() {
	*x = ModelItems{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelItems) ProtoMessage() {}

func (x *ModelItems) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelItems.ProtoReflect.Descriptor instead.
func (*ModelItems) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelItems) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// CreateModel — создание модели
type CreateModelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoId           string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Filename         string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	InputTokenPrice  int64                  `protobuf:"varint,4,opt,name=input_token_price,json=inputTokenPrice,proto3" json:"input_token_price,omitempty"`
	OutputTokenPrice int64                  `protobuf:"varint,5,opt,name=output_token_price,json=outputTokenPrice,proto3" json:"output_token_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateModelRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateModelRequest) GetInputTokenPrice() int64 {
	if x != nil {
		return x.InputTokenPrice
	}
	return 0
}

func (x *CreateModelRequest) GetOutputTokenPrice() int64 {
	if x != nil {
		return x.OutputTokenPrice
	}
	return 0
}

// UpdateModel — обновление модели (все optional)
type UpdateModelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RepoId           *string                `protobuf:"bytes,3,opt,name=repo_id,json=repoId,proto3,oneof" json:"repo_id,omitempty"`
	Filename         *string                `protobuf:"bytes,4,opt,name=filename,proto3,oneof" json:"filename,omitempty"`
	InputTokenPrice  *int64                 `protobuf:"varint,5,opt,name=input_token_price,json=inputTokenPrice,proto3,oneof" json:"input_token_price,omitempty"`
	OutputTokenPrice *int64                 `protobuf:"varint,6,opt,name=output_token_price,json=outputTokenPrice,proto3,oneof" json:"output_token_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateModelRequest) GetRepoId() string {
	if x != nil && x.RepoId != nil {
		return *x.RepoId
	}
	return ""
}

func (x *UpdateModelRequest) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *UpdateModelRequest) GetInputTokenPrice() int64 {
	if x != nil && x.InputTokenPrice != nil {
		return *x.InputTokenPrice
	}
	return 0
}

func (x *UpdateModelRequest) GetOutputTokenPrice() int64 {
	if x != nil && x.OutputTokenPrice != nil {
		return *x.OutputTokenPrice
	}
	return 0
}

// DeleteModel — удаление по uuid
type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\arepo_id\x18\x03 \x01(\tR\x06repoId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12*\n" +
	"\x11input_token_price\x18\x05 \x01(\x03R\x0finputTokenPrice\x12,\n" +
	"\x12output_token_price\x18\x06 \x01(\x03R\x10outputTokenPrice\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\n" +
	"ModelItems\x12(\n" +
	"\x06models\x18\x01 \x03(\v2\x10.model.ModelInfoR\x06models\"\xb7\x01\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12*\n" +
	"\x11input_token_price\x18\x04 \x01(\x03R\x0finputTokenPrice\x12,\n" +
	"\x12output_token_price\x18\x05 \x01(\x03R\x10outputTokenPrice\"\xaf\x02\n" +
	"\x12UpdateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1c\n" +
	"\arepo_id\x18\x03 \x01(\tH\x01R\x06repoId\x88\x01\x01\x12\x1f\n" +
	"\bfilename\x18\x04 \x01(\tH\x02R\bfilename\x88\x01\x01\x12/\n" +
	"\x11input_token_price\x18\x05 \x01(\x03H\x03R\x0finputTokenPrice\x88\x01\x01\x121\n" +
	"\x12output_token_price\x18\x06 \x01(\x03H\x04R\x10outputTokenPrice\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_repo_idB\v\n" +
	"\t_filenameB\x14\n" +
	"\x12_input_token_priceB\x15\n" +
	"\x13_output_token_price\"$\n" +
	"\x12DeleteModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x80\x02\n" +
	"\fModelService\x12:\n" +
	"\vCreateModel\x12\x19.model.CreateModelRequest\x1a\x10.model.ModelInfo\x12:\n" +
	"\vUpdateModel\x12\x19.model.UpdateModelRequest\x1a\x10.model.ModelInfo\x12@\n" +
	"\vDeleteModel\x12\x19.model.DeleteModelRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\tListModel\x12\x16.google.protobuf.Empty\x1a\x11.model.ModelItemsB\x16Z\x14./shared/proto/modelb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_proto_goTypes = []any{
	(*ModelInfo)(nil),             // 0: model.ModelInfo
	(*ModelItems)(nil),            // 1: model.ModelItems
	(*CreateModelRequest)(nil),    // 2: model.CreateModelRequest
	(*UpdateModelRequest)(nil),    // 3: model.UpdateModelRequest
	(*DeleteModelRequest)(nil),    // 4: model.DeleteModelRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_model_proto_depIdxs = []int32{
	5, // 0: model.ModelInfo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: model.ModelItems.models:type_name -> model.ModelInfo
	2, // 2: model.ModelService.CreateModel:input_type -> model.CreateModelRequest
	3, // 3: model.ModelService.UpdateModel:input_type -> model.UpdateModelRequest
	4, // 4: model.ModelService.DeleteModel:input_type -> model.DeleteModelRequest
	6, // 5: model.ModelService.ListModel:input_type -> google.protobuf.Empty
	0, // 6: model.ModelService.CreateModel:output_type -> model.ModelInfo
	0, // 7: model.ModelService.UpdateModel:output_type -> model.ModelInfo
	6, // 8: model.ModelService.DeleteModel:output_type -> google.protobuf.Empty
	1, // 9: model.ModelService.ListModel:output_type -> model.ModelItems
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	file_model_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
